from turtle import Turtle, Screen

# Draw a triangle, square, pentagon, hexagon,
# heptagon, octagon, nonagon and decagon

trt = Turtle()
trt.shapesize(5, 5)

trt.color("BlueViolet")
trt.screen.bgcolor("CadetBlue3")
trt.pen(pensize=10)


def draw_polygon_from_top(number_of_diagonals,pace):
    angle = 360/number_of_diagonals
    trt.rt(angle/2)
    for _ in range(number_of_diagonals-1):
        trt.fd(pace)
        trt.rt(angle)
    trt.fd(pace)
    trt.rt(angle/2)

def draw_polygon_from_base(number_of_diagonals,pace):
    angle = 360/number_of_diagonals
    # trt.fd(pace/2)
    for _ in range(number_of_diagonals):
        trt.fd(pace)
        trt.rt(angle)
    # trt.rt(angle)
    # trt.fd(pace/2)


    

def draw_triangle(pace):
    trt.rt(120/2)
    trt.fd(pace)
    trt.rt(120)
    trt.fd(pace)
    trt.rt(120)
    trt.fd(pace)
    trt.rt(120/2)

def draw_square(pace):
    trt.rt(90/2)
    trt.fd(pace)
    trt.rt(90)
    trt.fd(pace)  
    trt.rt(90)
    trt.fd(pace)  
    trt.rt(90) 
    trt.fd(pace)  
    trt.rt(90/2)

def pentagon(pace):
    trt.rt(72/2)
    trt.fd(pace)
    trt.rt(72)
    trt.fd(pace)  
    trt.rt(72)
    trt.fd(pace)  
    trt.rt(72)
    trt.fd(pace)  
    trt.rt(72)
    trt.fd(pace) 
    trt.rt(72/2)

def draw_hexagon(pace):
    trt.fd(pace/2)
    trt.rt(60)
    trt.fd(pace)  
    trt.rt(60)
    trt.fd(pace)  
    trt.rt(60)
    trt.fd(pace)  
    trt.rt(60)
    trt.fd(pace)  
    trt.rt(60)
    trt.fd(pace) 
    trt.rt(60)
    trt.fd(pace/2)

def draw_octagon(pace):
    trt.fd(pace/2)
    trt.rt(45)
    trt.fd(pace)  
    trt.rt(45)
    trt.fd(pace)  
    trt.rt(45)
    trt.fd(pace)  
    trt.rt(45)
    trt.fd(pace)  
    trt.rt(45)
    trt.fd(pace) 
    trt.rt(45)
    trt.fd(pace) 
    trt.rt(45)
    trt.fd(pace) 
    trt.rt(45)
    trt.fd(pace/2) 
def draw_decagon(pace):
    trt.fd(pace/2)
    trt.rt(36)
    trt.fd(pace)  
    trt.rt(36)
    trt.fd(pace)  
    trt.rt(36)
    trt.fd(pace)  
    trt.rt(36)
    trt.fd(pace)  
    trt.rt(36)
    trt.fd(pace) 
    trt.rt(36)
    trt.fd(pace) 
    trt.rt(36)
    trt.fd(pace) 
    trt.rt(36)
    trt.fd(pace) 
    trt.rt(36)
    trt.fd(pace) 
    trt.rt(36)
    trt.fd(pace/2) 

def draw_heptagon(pace):
    trt.rt(51.43/2)
    trt.fd(pace)  
    trt.rt(51.43)
    trt.fd(pace)  
    trt.rt(51.43)
    trt.fd(pace)  
    trt.rt(51.43)
    trt.fd(pace)  
    trt.rt(51.43)
    trt.fd(pace) 
    trt.rt(51.43)
    trt.fd(pace) 
    trt.rt(51.43)
    trt.fd(pace) 
    trt.rt(51.43/2)
def draw_nonagon(pace):
    trt.rt(40/2)
    trt.fd(pace)  
    trt.rt(40)
    trt.fd(pace)  
    trt.rt(40)
    trt.fd(pace)  
    trt.rt(40)
    trt.fd(pace)  
    trt.rt(40)
    trt.fd(pace) 
    trt.rt(40)
    trt.fd(pace) 
    trt.rt(40)
    trt.fd(pace) 
    trt.rt(40)
    trt.fd(pace) 
    trt.rt(40)
    trt.fd(pace) 
    trt.rt(40/2)


trt.rt(-90)
trt.up()
trt.fd(500)
trt.down()
trt.rt(90)
draw_polygon_from_base(3,200)
trt.color('red')
draw_polygon_from_base(4,200)
trt.color('blue')
draw_polygon_from_base(5,200)
trt.color('DarkOrchid')
draw_polygon_from_base(6,200)
trt.color('DarkSlateBlue')
draw_polygon_from_base(7,200)
trt.color('azure4')
draw_polygon_from_base(8,200)
trt.color('DarkBlue')
draw_polygon_from_base(9,200)
trt.color('CornflowerBlue')
draw_polygon_from_base(10,200)
trt.color('DarkOrange')
draw_polygon_from_base(11, 200)
trt.color('firebrick')
draw_polygon_from_base(12, 200)
trt.color('goldenrod')
draw_polygon_from_base(13, 200)
trt.color('green4')
draw_polygon_from_base(14, 200)
trt.color('hotpink')
draw_polygon_from_base(15, 200)
trt.color('indigo')
draw_polygon_from_base(16, 200)
trt.color('khaki4')
draw_polygon_from_base(17, 200)
trt.color('lightcoral')
draw_polygon_from_base(18, 200)
trt.color('maroon')
draw_polygon_from_base(19, 200)
trt.color('coral4')
draw_polygon_from_base(20, 200)
# pentagon(200)
# trt.color('green')
# draw_hexagon(200)
# trt.color('yellow')
# draw_heptagon(200)
# trt.color('black')
# draw_octagon(200)
# trt.color('purple')
# draw_nonagon(200)
# trt.color('brown')
# draw_decagon(200)



ms = Screen()
ms.exitonclick()
